###
@id =6
PUT http://localhost:8080/api/v1/admin/email-history/{{id}}
Content-Type: application/json

{
  "recipientEmail": "updated-recipientEmail",
  "subject": "updated-subject",
  "message": "updated-message-text",
  "status": "SENT"
}

<> 2024-07-24T204259.200.json
<> 2024-07-24T204045.200.json
<> 2024-07-24T203900.200.json
<> 2024-07-24T203805.200.json
<> 2024-07-24T203731.400.json